"""Convert VNLP detection dataset to YOLO format.

Reads dataset_manifest.json, extracts bbox from each filename,
and writes YOLO-format label files alongside copied images.

Output layout:
    data/yolo-vnlp/
        data.yaml
        train/images/*.jpg   (symlinks or copies)
        train/labels/*.txt
        val/images/*.jpg
        val/labels/*.txt
        test/images/*.jpg
        test/labels/*.txt

Label format (YOLO):  class cx cy w h  (normalized 0-1, class 0 = plate)
Filename format:      {idx}_{frame}_{cls}_{plate}_{x1}_{y1}_{x2}_{y2}.jpg
"""
from __future__ import annotations

import json
import os
import shutil
import sys
import time
from pathlib import Path

import cv2

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = PROJECT_ROOT / "data" / "processed" / "dataset_manifest.json"
EXTERNAL_DIR = PROJECT_ROOT / "data" / "external"
OUT_DIR = PROJECT_ROOT / "data" / "yolo-vnlp"

SPLITS = ("train", "val", "test")


def parse_bbox_from_filename(stem: str) -> tuple[int, int, int, int] | None:
    """Extract absolute bbox coords from VNLP filename stem.

    Pattern: {idx}_{frame}_{cls}_{plate}_{x1}_{y1}_{x2}_{y2}
    Returns (x1, y1, x2, y2) or None if parsing fails.
    """
    parts = stem.split("_")
    if len(parts) < 8:
        return None
    try:
        x1 = int(parts[4])
        y1 = int(parts[5])
        x2 = int(parts[6])
        y2 = int(parts[7])
        return x1, y1, x2, y2
    except ValueError:
        return None


def bbox_to_yolo(x1: int, y1: int, x2: int, y2: int, w: int, h: int) -> tuple[float, float, float, float]:
    """Convert absolute bbox to YOLO normalized format (cx, cy, bw, bh)."""
    cx = ((x1 + x2) / 2) / w
    cy = ((y1 + y2) / 2) / h
    bw = (x2 - x1) / w
    bh = (y2 - y1) / h
    return cx, cy, bw, bh


def process_split(entries: list[dict], split: str) -> dict:
    """Process all entries for a given split. Returns statistics."""
    split_entries = [e for e in entries if e["split"] == split]
    images_dir = OUT_DIR / split / "images"
    labels_dir = OUT_DIR / split / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    total = 0
    skipped_missing = 0
    skipped_parse = 0
    skipped_invalid = 0
    processed = 0

    t0 = time.time()

    for i, entry in enumerate(split_entries):
        # Resolve source image path
        rel = entry["path"].replace("\\", "/")
        src_path = EXTERNAL_DIR / rel
        if not src_path.exists():
            skipped_missing += 1
            continue

        total += 1

        stem = src_path.stem
        bbox = parse_bbox_from_filename(stem)
        if bbox is None:
            skipped_parse += 1
            continue

        x1, y1, x2, y2 = bbox

        # Get image dimensions
        img = cv2.imread(str(src_path))
        if img is None:
            skipped_missing += 1
            continue
        h, w = img.shape[:2]

        # Validate bbox
        if x2 <= x1 or y2 <= y1 or x1 < 0 or y1 < 0 or x2 > w or y2 > h:
            # Clamp to image bounds
            x1 = max(0, x1)
            y1 = max(0, y1)
            x2 = min(w, x2)
            y2 = min(h, y2)
            if x2 <= x1 or y2 <= y1:
                skipped_invalid += 1
                continue

        cx, cy, bw, bh = bbox_to_yolo(x1, y1, x2, y2, w, h)

        # Copy image to yolo layout
        dst_img = images_dir / src_path.name
        if not dst_img.exists():
            shutil.copy2(src_path, dst_img)

        # Write label file
        label_path = labels_dir / (stem + ".txt")
        label_path.write_text(f"0 {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n", encoding="utf-8")

        processed += 1

        if (i + 1) % 2000 == 0:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed
            eta = (len(split_entries) - i - 1) / rate
            print(f"  [{split}] {i+1}/{len(split_entries)} ({rate:.0f} img/s, ETA {eta:.0f}s)")

    elapsed = time.time() - t0
    return {
        "split": split,
        "total_entries": len(split_entries),
        "processed": processed,
        "skipped_missing": skipped_missing,
        "skipped_parse": skipped_parse,
        "skipped_invalid": skipped_invalid,
        "elapsed_s": round(elapsed, 1),
    }


def write_data_yaml() -> None:
    """Write data.yaml for ultralytics YOLO training."""
    yaml_content = f"""# VNLP License Plate Detection Dataset
# Generated by scripts/convert-vnlp-to-yolo.py

path: {OUT_DIR.as_posix()}
train: train/images
val: val/images
test: test/images

nc: 1
names:
  0: plate
"""
    yaml_path = OUT_DIR / "data.yaml"
    yaml_path.write_text(yaml_content, encoding="utf-8")
    print(f"  Written: {yaml_path}")


def main() -> None:
    print(f"[convert-vnlp-to-yolo] Output: {OUT_DIR}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with open(MANIFEST_PATH, encoding="utf-8") as f:
        manifest = json.load(f)
    entries = manifest["entries"]

    print(f"  Total manifest entries: {len(entries)}")

    stats = []
    for split in SPLITS:
        print(f"\nProcessing split: {split}")
        s = process_split(entries, split)
        stats.append(s)
        print(f"  {split}: {s['processed']} OK, {s['skipped_missing']} missing, "
              f"{s['skipped_parse']} parse-error, {s['skipped_invalid']} invalid bbox, "
              f"elapsed {s['elapsed_s']}s")

    write_data_yaml()

    # Save stats
    stats_path = OUT_DIR / "conversion_stats.json"
    stats_path.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(f"\n[convert-vnlp-to-yolo] Done. Stats saved to {stats_path}")

    total_ok = sum(s["processed"] for s in stats)
    print(f"  Total images processed: {total_ok}")


if __name__ == "__main__":
    main()
